=== euroargodev/VirtualFleet/schemas/VF-ArgoFloat-Configuration.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://raw.githubusercontent.com/euroargodev/VirtualFleet/json-schemas-FloatConfiguration/schemas/VF-ArgoFloat-Configuration.json",
  "title": "VirtualFleet Argo Float configuration",
  "description": "A set of data documenting a virtual Argo Float configuration to be used in a VirtualFleet simulation",
  "format_version": {
    "const": "2.0"
  },
  "required": [
    "created",
    "version",
    "name",
    "parameters"
  ],
  "type": "object",
  "properties": {
    "created": {
      "description": "UTC creation datetime of the configuration file",
      "type": "string",
      "format": "date-time"
    },
    "version": {
      "description": "Version name of the configuration parameter set",
      "type": "string"
    },
    "name": {
      "description": "Internal shortname of the configuration parameter set. Used to load a configuration JSON file with the 'FloatConfiguration' class.",
      "type": "string"
    },
    "parameters": {
      "description": "List of virtual Argo floats configuration parameters",
      "type": "array",
      "allOf": [
        {
          "items": {
            "$ref": "#/$defs/parameter"
          }
        }
      ]
    }
  },
  "$defs": {
    "parameter": {
      "title": "VirtualFleet Argo Float configuration required parameter",
      "description": "A set of data documenting one parameter for a virtual Argo Float configuration",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "enum": [
            "cycle_duration",
            "life_expectancy",
            "parking_depth",
            "profile_depth",
            "vertical_speed",
            "area_cycle_duration",
            "area_parking_depth",
            "area_xmax",
            "area_xmin",
            "area_ymax",
            "area_ymin"
          ]
        },
        "value": {
          "type": [
            "string",
            "number"
          ]
        },
        "description": {
          "type": "string"
        },
        "meta": {
          "$ref": "#/$defs/parameter_metadata"
        }
      },
      "required": [
        "name",
        "value"
      ]
    },
    "parameter_metadata": {
      "title": "Set of meta-data documenting one parameter for a virtual Argo Float configuration",
      "required": [],
      "type": "object",
      "properties": {
        "unit": {
          "type": "string"
        },
        "dtype": {
          "type": "string",
          "enum": [
            "float",
            "int"
          ]
        },
        "teckkey": {
          "type": "string"
        }
      }
    }
  },
  "version": 2
}

=== euroargodev/VirtualFleet/virtualargofleet/assets/FloatConfiguration_local_change.json
{
    "created": "2024-03-06T16:05:31.448953+00:00",
    "version": "2.0",
    "name": "local-change",
    "parameters": [
        {
            "name": "area_cycle_duration",
            "value": 120.0,
            "description": "Maximum length of float complete cycle in AREA",
            "meta": {
                "unit": "hours",
                "dtype": "float",
                "techkey": "CONFIG_CycleTime_hours"
            }
        },
        {
            "name": "area_parking_depth",
            "value": 1000.0,
            "description": "Drifting depth in AREA",
            "meta": {
                "unit": "m",
                "dtype": "float",
                "techkey": "CONFIG_ParkPressure_dbar"
            }
        },
        {
            "name": "area_xmax",
            "value": -48.0,
            "description": "AREA Eastern bound",
            "meta": {
                "unit": "deg_longitude",
                "dtype": "float",
                "techkey": ""
            }
        },
        {
            "name": "area_xmin",
            "value": -75.0,
            "description": "AREA Western bound",
            "meta": {
                "unit": "deg_longitude",
                "dtype": "float",
                "techkey": ""
            }
        },
        {
            "name": "area_ymax",
            "value": 45.5,
            "description": "AREA Northern bound",
            "meta": {
                "unit": "deg_latitude",
                "dtype": "float",
                "techkey": ""
            }
        },
        {
            "name": "area_ymin",
            "value": 33.0,
            "description": "AREA Southern bound",
            "meta": {
                "unit": "deg_latitude",
                "dtype": "float",
                "techkey": ""
            }
        },
        {
            "name": "cycle_duration",
            "value": 240.0,
            "description": "Maximum length of float complete cycle",
            "meta": {
                "unit": "hours",
                "dtype": "float",
                "techkey": "CONFIG_CycleTime_hours"
            }
        },
        {
            "name": "life_expectancy",
            "value": 200,
            "description": "Maximum number of completed cycle",
            "meta": {
                "unit": "cycle",
                "dtype": "int",
                "techkey": "CONFIG_MaxCycles_NUMBER"
            }
        },
        {
            "name": "parking_depth",
            "value": 1000.0,
            "description": "Drifting depth",
            "meta": {
                "unit": "m",
                "dtype": "float",
                "techkey": "CONFIG_ParkPressure_dbar"
            }
        },
        {
            "name": "profile_depth",
            "value": 2000.0,
            "description": "Maximum profile depth",
            "meta": {
                "unit": "m",
                "dtype": "float",
                "techkey": "CONFIG_ProfilePressure_dbar"
            }
        },
        {
            "name": "vertical_speed",
            "value": 0.09,
            "description": "Vertical profiling speed",
            "meta": {
                "unit": "m/s",
                "dtype": "float",
                "techkey": ""
            }
        }
    ],
    "$schema": "https://raw.githubusercontent.com/euroargodev/json-schemas-FloatConfiguration/schemas/VF-ArgoFloat-Configuration.json"
}

=== euroargodev/VirtualFleet/virtualargofleet/assets/FloatConfiguration_default.json
{
    "created": "2024-03-07T08:44:43.560904+00:00",
    "version": "2.0",
    "name": "default",
    "parameters": [
        {
            "name": "cycle_duration",
            "value": 240.0,
            "description": "Maximum length of float complete cycle",
            "meta": {
                "unit": "hours",
                "dtype": "float",
                "techkey": "CONFIG_CycleTime_hours",
                "$schema": "https://raw.githubusercontent.com/euroargodev/VirtualFleet/json-schemas-FloatConfiguration/schemas/VF-ArgoFloat-Configuration.json#parameter_metadata"
            },
            "$schema": "https://raw.githubusercontent.com/euroargodev/VirtualFleet/json-schemas-FloatConfiguration/schemas/VF-ArgoFloat-Configuration.json#required_parameter"
        },
        {
            "name": "life_expectancy",
            "value": 200,
            "description": "Maximum number of completed cycle",
            "meta": {
                "unit": "cycle",
                "dtype": "int",
                "techkey": "CONFIG_MaxCycles_NUMBER",
                "$schema": "https://raw.githubusercontent.com/euroargodev/VirtualFleet/json-schemas-FloatConfiguration/schemas/VF-ArgoFloat-Configuration.json#parameter_metadata"
            },
            "$schema": "https://raw.githubusercontent.com/euroargodev/VirtualFleet/json-schemas-FloatConfiguration/schemas/VF-ArgoFloat-Configuration.json#required_parameter"
        },
        {
            "name": "parking_depth",
            "value": 1000.0,
            "description": "Drifting depth",
            "meta": {
                "unit": "m",
                "dtype": "float",
                "techkey": "CONFIG_ParkPressure_dbar",
                "$schema": "https://raw.githubusercontent.com/euroargodev/VirtualFleet/json-schemas-FloatConfiguration/schemas/VF-ArgoFloat-Configuration.json#parameter_metadata"
            },
            "$schema": "https://raw.githubusercontent.com/euroargodev/VirtualFleet/json-schemas-FloatConfiguration/schemas/VF-ArgoFloat-Configuration.json#required_parameter"
        },
        {
            "name": "profile_depth",
            "value": 2000.0,
            "description": "Maximum profile depth",
            "meta": {
                "unit": "m",
                "dtype": "float",
                "techkey": "CONFIG_ProfilePressure_dbar",
                "$schema": "https://raw.githubusercontent.com/euroargodev/VirtualFleet/json-schemas-FloatConfiguration/schemas/VF-ArgoFloat-Configuration.json#parameter_metadata"
            },
            "$schema": "https://raw.githubusercontent.com/euroargodev/VirtualFleet/json-schemas-FloatConfiguration/schemas/VF-ArgoFloat-Configuration.json#required_parameter"
        },
        {
            "name": "vertical_speed",
            "value": 0.09,
            "description": "Vertical profiling speed",
            "meta": {
                "unit": "m/s",
                "dtype": "float",
                "techkey": "",
                "$schema": "https://raw.githubusercontent.com/euroargodev/VirtualFleet/json-schemas-FloatConfiguration/schemas/VF-ArgoFloat-Configuration.json#parameter_metadata"
            },
            "$schema": "https://raw.githubusercontent.com/euroargodev/VirtualFleet/json-schemas-FloatConfiguration/schemas/VF-ArgoFloat-Configuration.json#required_parameter"
        }
    ],
    "$schema": "https://raw.githubusercontent.com/euroargodev/VirtualFleet/json-schemas-FloatConfiguration/schemas/VF-ArgoFloat-Configuration.json"
}
